### ISSUE TITLE
manualy adding url to crawl

### ISSUE THREAD

**Issue by Placebo** [cgiffard/node-simplecrawler#164]
I dont know why this code not working and not fetching my custom urls

```javascript
var Crawler = require("simplecrawler");

var myCrawler = new Crawler("www.digikala.com");

myCrawler.interval = 5000; // Ten seconds
myCrawler.maxConcurrency = 2;
myCrawler.maxDepth = 1;

myCrawler.discoverResources = function(buf, queueItem) {
myCrawler.queueURL('http://www.digikala.com/Product/DKP-70875/Wdx-Flame-1046-Head-Wear/دستمال-سر-و-گردن-Wdx-مدل-Flame-کد-1046/', queueItem);
myCrawler.queueURL('http://www.digikala.com/Product/DKP-70877/Wdx-Nepal-1097-Head-Wear/دستمال-سر-و-گردن-Wdx-مدل-Nepal-کد-1097/', queueItem);
myCrawler.queueURL('http://www.digikala.com/Product/DKP-70925/ASUS-A555LD-A/لپ-تاپ-ايسوس-مدل-A555LD/', queueItem);
   return [];
};

    
myCrawler.on("fetchcomplete", function(queueItem) {
    console.log("Completed fetching resource:", queueItem.url);
});


myCrawler.start();
```

**Comment by cgiffard** [comment]
Hey — thanks for filing an issue.

You're ultimately not using `discoverResources` in the correct way — this is intended to be a function you provide for discovering arbitrary resources based on an input buffer, and replacing it with a function that returns an empty list will only result in those three URLs being discovered, ever.

Instead, you should add these URLs to the queue manually:

```js

var Crawler = require("simplecrawler"),
    myCrawler = new Crawler("www.digikala.com");

crawler.queue.add("http", "www.digikala.com", 80, "/Product/DKP-70925/ASUS-A555LD-A/لپ-تاپ-ايسوس-مدل-A555LD/", 0);

// the rest of your code goes here —

myCrawler.start();
```

Let me know how that goes. If you get stuck, please just reopen the issue.

**Comment by Placebo** [comment]
@cgiffard thanks
but how can i prevent the default discovery?
i want your module just do the fetch for my custom added urls - not crawl for more resources
i mean in 1 depth crawl

**Comment by cgiffard** [comment]
Well, you can do: `crawler.discoverResources = function() {}` — but I suspect you're using the wrong tool if you just want to download a list of URLs. It'll work, but it might be a bit of a blunt instrument.

**Comment by Placebo** [comment]
I want to make use of benefit of your caching system and sending request script

i did the following   : 
```nodejs

var Crawler = require("simplecrawler");

var myCrawler = new Crawler("www.digikala.com");



var urls = [];

urls.push("/Product/DKP-78723/Huawei-Ascend-G620S-L01/%DA%AF%D9%88%D8%B4%D9%8A-%D9%85%D9%88%D8%A8%D8%A7%D9%8A%D9%84-%D9%87%D9%88%D8%A2%D9%88%D9%8A-%D8%A7%D8%B3%D9%86%D8%AF-G620S");
urls.push("/Product/DKP-12160/Huawei-U8685D-Ascend-Y210/%DA%AF%D9%88%D8%B4%D9%8A-%D9%85%D9%88%D8%A8%D8%A7%D9%8A%D9%84-%D9%87%D9%88%D8%A2%D9%88%D9%8A-%D9%8A%D9%88-8685-%D8%AF%D9%8A-%D8%A7%D8%B3%D9%86%D8%AF-%D9%88%D8%A7%D9%8A-210");
urls.push("/Product/DKP-41590/Samsung-Galaxy-Note-4-N910H-32GB/%DA%AF%D9%88%D8%B4%D9%8A-%D9%85%D9%88%D8%A8%D8%A7%D9%8A%D9%84-%D8%B3%D8%A7%D9%85%D8%B3%D9%88%D9%86%DA%AF-%DA%AF%D9%84%DA%A9%D8%B3%D9%8A-%D9%86%D9%88%D8%AA-4-N910H");
urls.push("/Product/DKP-14997/Samsung-Galaxy-S4-I9500-16GB/%DA%AF%D9%88%D8%B4%D9%8A-%D9%85%D9%88%D8%A8%D8%A7%D9%8A%D9%84-%D8%B3%D8%A7%D9%85%D8%B3%D9%88%D9%86%DA%AF-%DA%AF%D9%84%DA%A9%D8%B3%D9%8A-%D8%A7%D8%B3-4-%D8%A2%D9%8A-9500-16-%DA%AF%D9%8A%DA%AF%D8%A7%D8%A8%D8%A7%D9%8A%D8%AA");
myCrawler.discoverResources = function() {}
for (var i = 0; i < urls.length; i++) {
	
	myCrawler.queue.add("http", "www.digikala.com", 80, urls[i], 0);
};
myCrawler.on("fetchcomplete", function(queueItem) {
    console.log("Completed fetching resource:", queueItem.url);
});

myCrawler.start();
```

got this error : 
```bash
/Users/sinamiandashti/projects/rango/node_modules/simplecrawler/lib/crawler.js:657
	resources.forEach(function(url){ crawler.queueURL(url,queueItem); });
	         ^
TypeError: Cannot read property 'forEach' of undefined
    at Crawler.queueLinkedItems (/Users/sinamiandashti/projects/rango/node_modules/simplecrawler/lib/crawler.js:657:11)
    at processReceivedData (/Users/sinamiandashti/projects/rango/node_modules/simplecrawler/lib/crawler.js:989:13)
    at IncomingMessage.receiveData (/Users/sinamiandashti/projects/rango/node_modules/simplecrawler/lib/crawler.js:1050:4)
    at IncomingMessage.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at IncomingMessage.Readable.push (_stream_readable.js:126:10)
    at HTTPParser.parserOnBody (_http_common.js:132:22)
    at Socket.socketOnData (_http_client.js:317:20)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
```

@cgiffard thanks for fast responses

**Comment by cgiffard** [comment]
My apologies — made a mistake with the first suggestion by neglecting to return from the discover function. :)

Change it to:

```js
myCrawler.discoverResources = function() { return []; }
```
