### ISSUE TITLE
A name is required to create a cookie

### ISSUE THREAD

**Issue by herkyl** [cgiffard/node-simplecrawler#184]
After running simplecrawler throughout the night it crashed multiple times on the same error:
```
Error: A name is required to create a cookie.
    at new Cookie (/root/s-crawler/node_modules/simplecrawler/lib/cookies.js:291:15)
    at Function.Cookie.fromString (/root/s-crawler/node_modules/simplecrawler/lib/cookies.js:358:12)
    at CookieJar.add (/root/s-crawler/node_modules/simplecrawler/lib/cookies.js:68:28)
    at /root/s-crawler/node_modules/simplecrawler/lib/cookies.js:245:13
    at Array.forEach (native)
    at CookieJar.addFromHeaders (/root/s-crawler/node_modules/simplecrawler/lib/cookies.js:244:13)
    at Crawler.handleResponse (/root/s-crawler/node_modules/simplecrawler/lib/crawler.js:1005:25)
    at ClientRequest.<anonymous> (/root/s-crawler/node_modules/simplecrawler/lib/crawler.js:915:25)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:415:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at Socket.socketOnData (_http_client.js:305:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
```

**Comment by evenisse** [comment]
I have a similar issue :

/Users/dev/code/crawler/crawler/node_modules/simplecrawler/lib/cookies.js:329
        throw new Error("String must be supplied to generate a cookie.");
        ^

Error: String must be supplied to generate a cookie.
    at Function.Cookie.fromString (/Users/dev/code/crawler/crawler/node_modules/simplecrawler/lib/cookies.js:329:15)
    at CookieJar.add (/Users/dev/code/crawler/crawler/node_modules/simplecrawler/lib/cookies.js:68:28)
    at /Users/dev/code/crawler/crawler/node_modules/simplecrawler/lib/cookies.js:245:13
    at Array.forEach (native)
    at CookieJar.addFromHeaders (/Users/dev/code/crawler/crawler/node_modules/simplecrawler/lib/cookies.js:244:13)
    at Crawler.handleResponse (/Users/dev/code/crawler/crawler/node_modules/simplecrawler/lib/crawler.js:1005:25)
    at ClientRequest.<anonymous> (/Users/dev/code/crawler/crawler/node_modules/simplecrawler/lib/crawler.js:915:25)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)

**Comment by fredrikekelund** [comment]
This is a tricky one. Most likely it's simply due to a malformed `Set-Cookie` header. I think it's a bit overkill for the crawler to throw an error because of this, what with external headers being outside of the developer's control and all. Perhaps a better solution would be to raise an event when there's an error. I'll look into fixing it!

**Comment by fredrikekelund** [comment]
I've pushed a fix for this - when the crawler encounters malformed cookies, it won't add them, and it will emit a "cookieerror" event with the signature (queueItem, error, setCookieHeader). This enabled the developer to do manual work with the cookie as needed.

**Comment by herkyl** [comment]
Thanks @fredrikekelund
