### ISSUE TITLE
error during crawling site

### ISSUE THREAD

**Issue by hbakhtiyor** [cgiffard/node-simplecrawler#264]
i got error during crawling http://afscanada.org/ site, i used your example with some changes

```js
var Crawler = require("simplecrawler").Crawler;
var cheerio = require("cheerio");

var myCrawler = new Crawler("afscanada.org");

myCrawler.discoverResources = function(buffer, queueItem) {
    var $ = cheerio.load(buffer.toString("utf8"));

    return $("a[href]").map(function (element) {
        return $(element).attr("href");
    });
};

myCrawler.on("fetchstart", function(queueItem) {
    console.log("Starting request for:", queueItem.url);
});

myCrawler.on("fetchcomplete", function(queueItem, responseBuffer, response) {
    console.log("I just received %s (%d bytes)", queueItem.url, responseBuffer.length);
    console.log("It was a resource of type %s", response.headers["content-type"]);
});

// Fire callback
myCrawler.on("complete", function() {
    console.log("Done!");
});

// Start Crawl
myCrawler.start();
```

```json
  "dependencies": {
    "cheerio": "^0.20.0",
    "simplecrawler": "^0.6.2"
  }
```

```
demo/node_modules/simplecrawler/lib/crawler.js:731
    resources.forEach(function(url) {
              ^
TypeError: undefined is not a function
    at Crawler.queueLinkedItems (demo/node_modules/simplecrawler/lib/crawler.js:731:15)
    at IncomingMessage.processReceivedData (demo/node_modules/simplecrawler/lib/crawler.js:1106:25)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

node version: `v0.12.4`

**Comment by hbakhtiyor** [comment]
ah, fixed, problem was in your snippet of code
the `map` callback signature is `index, element` and `element` equal to `this` inside callback.
also `map` return their own object, not array

final result is
```js
    return $("a[href]").map(function () {
        return $(this).attr("href");
    }).get();
```
