### ISSUE TITLE
your simple example does not work

### ISSUE THREAD

**Issue by liesislukas** [cgiffard/node-simplecrawler#307]
- [x] I have read the contributing guidelines.

### What happened (Observed behaviour)
```
var crawler = Crawler('http://www.example.com/').on('fetchcomplete', function () {
TypeError: Cannot read property 'on' of undefined
```

### What should happen (Expected behaviour)

return some response

### Steps to reproduce the problem (include code examples)

`npm i simplecrawler` and then:
```
let Crawler = require('simplecrawler');

var crawler = Crawler('http://www.example.com/')
  .on('fetchcomplete', function () {
    console.log('Fetched a resource!');
  });
```

### more test cases

Interesting that it works *sometimes* with `new`:

```js
let Crawler = require('simplecrawler');

var crawler = new Crawler('http://www.example.com/');
crawler.on('queueerror', (errorData, URLData) => {
  console.log('#aa queueerror::: ', errorData, URLData);
});
crawler.on('fetchcomplete', (queueItem, responseBody, responseObject) => {
  console.log('fetchcomplete!');
});
crawler.on('fetchclienterror', (queueItem, errorData) => {
  console.log('fetchclienterror::: ', queueItem, errorData);
});
crawler.start();
```

response:

```
fetchclienterror::: 

 { url: 'http://http://www.example.com//',
  protocol: 'http',
  host: 'http://www.example.com/',
  port: 80,
  path: '/',
  depth: 1,
  fetched: true,
  status: 'failed',
  stateData: { code: 599 } }

 { Error: getaddrinfo ENOTFOUND http://www.example.com/ http://www.example.com/:80
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:79:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'http://www.example.com/',
  host: 'http://www.example.com/',
  port: 80 }
```

if i change url w/o http:// like: `www.example.com` then response is:

```
fetchcomplete!
```

if url = `https://github.com/cgiffard/node-simplecrawler/issues`

response:

```
fetchclienterror:::  { url: 'http://https://github.com/cgiffard/node-simplecrawler/issues/',
  protocol: 'http',
  host: 'https://github.com/cgiffard/node-simplecrawler/issues',
  port: 80,
  path: '/',
  depth: 1,
  fetched: true,
  status: 'failed',
  stateData: { code: 599 } } { Error: getaddrinfo ENOTFOUND https://github.com/cgiffard/node-simplecrawler/issues https://github.com/cgiffard/node-simplecrawler/issues:80
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:79:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'https://github.com/cgiffard/node-simplecrawler/issues',
  host: 'https://github.com/cgiffard/node-simplecrawler/issues',
  port: 80 }
```

if url = `github.com/cgiffard/node-simplecrawler/issues`

```
fetchclienterror:::  { url: 'http://github.com/cgiffard/node-simplecrawler/issues/',
  protocol: 'http',
  host: 'github.com/cgiffard/node-simplecrawler/issues',
  port: 80,
  path: '/',
  depth: 1,
  fetched: true,
  status: 'failed',
  stateData: { code: 599 } } { Error: getaddrinfo ENOTFOUND github.com/cgiffard/node-simplecrawler/issues github.com/cgiffard/node-simplecrawler/issues:80
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:79:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'github.com/cgiffard/node-simplecrawler/issues',
  host: 'github.com/cgiffard/node-simplecrawler/issues',
  port: 80 }
```

if url = `http://github.com`

```
fetchclienterror:::  { url: 'http://http://github.com/',
  protocol: 'http',
  host: 'http://github.com',
  port: 80,
  path: '/',
  depth: 1,
  fetched: true,
  status: 'failed',
  stateData: { code: 599 } } { Error: getaddrinfo ENOTFOUND http://github.com http://github.com:80
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:79:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'http://github.com',
  host: 'http://github.com',
  port: 80 }
```

if url = `github.com` i don't get *anything* so i added all event listeners and added `crawler.maxConcurrency = 1;` and `crawler.maxDepth = 3;` 

```js
let Crawler = require('simplecrawler');

var crawler = new Crawler('github.com');
crawler.on('queueerror', (errorData, URLData) => {
  console.log('#aa queueerror::: ', errorData, URLData);
});
crawler.on('fetchcomplete', (queueItem, responseBody, responseObject) => {
  console.log('fetchcomplete!');
});
crawler.on('fetchclienterror', (queueItem, errorData) => {
  console.log('fetchclienterror::: ', queueItem, errorData);
});
crawler.on('crawlstart', () => {
  console.log('#w4fe crawlstart::: ');
});
crawler.on('queueadd', (queueItem) => {
  console.log('#w4fe queueadd::: ', queueItem);
});
crawler.on('queueduplicate', (URLData) => {
  console.log('#w4fe queueduplicate::: ', URLData);
});
crawler.on('queueerror', (errorData, URLData) => {
  console.log('#w4fe queueerror::: ', errorData, URLData);
});
crawler.on('robotstxterror', (error) => {
  console.log('#w4fe robotstxterror::: ', error);
});
crawler.on('fetchstart', (queueItem, requestOptions) => {
  console.log('#w4fe fetchstart::: ');
});
crawler.on('fetchheaders', (queueItem, responseObject) => {
  console.log('#w4fe fetchheaders::: ');
});
crawler.on('cookieerror', (queueItem, error, setCookieHeader) => {
  console.log('#w4fe cookieerror::: ', queueItem, error, setCookieHeader);
});
crawler.on('fetchdisallowed', (x, y, z) => {
  console.log('#w4fe fetchdisallowed::: ');
});
crawler.on('fetchdataerror', (x, y, z) => {
  console.log('#w4fe fetchdataerror::: ');
});
crawler.on('fetchredirect', (x, y, z) => {
  console.log('#w4fe fetchredirect::: ');
});
crawler.on('fetch404', (x, y, z) => {
  console.log('#w4fe fetch404::: ');
});
crawler.on('fetch410', (x, y, z) => {
  console.log('#w4fe fetch410::: ');
});
crawler.on('fetcherror', (x, y, z) => {
  console.log('#w4fe fetcherror::: ');
});
crawler.on('gziperror', (x, y, z) => {
  console.log('#w4fe gziperror::: ');
});
crawler.on('fetchtimeout', (x, y, z) => {
  console.log('#w4fe fetchtimeout::: ');
});
crawler.on('fetchclienterror', (x, y, z) => {
  console.log('#w4fe fetchclienterror::: ', x, y, z);
});
crawler.on('discoverycomplete', (x, y, z) => {
  console.log('#w4fe discoverycomplete::: ');
});
crawler.on('complete', (x, y, z) => {
  console.log('#w4fe complete::: ');
});

crawler.maxConcurrency = 1;
crawler.maxDepth = 3;
crawler.start();

```

and i got this:
```
#w4fe crawlstart::: 
*** run get_domains_from_resources ***
#w4fe fetchstart::: 
#w4fe fetchheaders::: 
#w4fe fetchredirect::: 
#w4fe queueadd:::  { url: 'https://github.com/',
  protocol: 'https',
  host: 'github.com',
  port: 80,
  path: '/',
  depth: 1,
  fetched: false,
  status: 'queued',
  stateData: {} }
#w4fe fetchstart::: 
#w4fe fetchheaders::: 
#w4fe fetchredirect::: 
#w4fe queueduplicate:::  { protocol: 'https',
  host: 'github.com',
  port: 80,
  path: '/',
  uriPath: '/',
  depth: 1 }
#w4fe complete::: 
```

1. would love to see examples how to fetch e.g. `https://github.com/cgiffard/node-simplecrawler/` and everything that is inside, like issues etc. all inner pages w/o fetching like all github.com
2. why it doesn't work with .on from 1st example on your readme?
3. should i add http:// https:// or no?

**Comment by fredrikekelund** [comment]
Hi! This issue seems to be due to a discrepancy between the master branch here on GitHub and the latest release on npm. We're nearing the 1.0.0 release here, but on npm, we're still at 0.7.0. With the 1.0.0 release, we've changed the arguments that the constructor accepts to be just a single URL, as opposed to the URL parts that we used previously. If you refer to the README on npm, it should hopefully point you in the right direction!

As for point 2, you can use a fetch condition to check that the uriPath of the incoming parsedURL starts with eg. "cgiffard/simplecrawler". That should prevent the crawler from going and fetching all of github.com! :)

Let me know if you have any more issues!

**Comment by liesislukas** [comment]
yes it was because npm has diff version then github and i read github's docs
