### ISSUE TITLE
example doesn't work - "fetchcomplete" is not triggered...

### ISSUE THREAD

**Issue by eyal13579** [cgiffard/node-simplecrawler#312]
example doesn't work - "fetchcomplete" is not triggered...

    .on("fetchcomplete", function () {
    ^

TypeError: Cannot read property 'on' of undefined
    at Object.<anonymous> (.....\test.js:6:5)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by cgiffard** [comment]
Ah, this is an issue relating to the difference in versions between npm (0.7) and GitHub (nearing 1.0). My fault, sorry! We'll have a release soon. In the meantime you can either install directly from GitHub or refer to the readme on npm:
https://www.npmjs.com/package/simplecrawler
