### ISSUE TITLE
Crawling a website which returns invalid port?

### ISSUE THREAD

**Issue by ibexofentropy** [cgiffard/node-simplecrawler#320]
Crawler says
```
/home/cat/Dropbox/firm-email-crawler/node_modules/simplecrawler/lib/crawler.js:1124
            throw e;
            ^

RangeError: "port" option should be >= 0 and < 65536: 0862933485
    at lookupAndConnect (net.js:954:13)
    at Socket.connect (net.js:929:5)
    at Agent.exports.connect.exports.createConnection (net.js:70:35)
    at Agent.createSocket (_http_agent.js:187:26)
    at Agent.addRequest (_http_agent.js:149:10)
    at new ClientRequest (_http_client.js:158:16)
    at Object.exports.request (http.js:31:10)
    at /home/cat/Dropbox/firm-email-crawler/node_modules/simplecrawler/lib/crawler.js:1119:40
    at FetchQueue.update (/home/cat/Dropbox/firm-email-crawler/node_modules/simplecrawler/lib/queue.js:226:9)
    at Crawler.fetchQueueItem (/home/cat/Dropbox/firm-email-crawler/node_modules/simplecrawler/lib/crawler.js:1096:19)
```
on http://www.sieuthiled.org

**Comment by cgiffard** [comment]
Good catch. Will add to the test suite!
