### ISSUE TITLE
Unable to modify requestOptions.ciphers via "fetchstart" event

### ISSUE THREAD

**Issue by EyePulp** [cgiffard/node-simplecrawler#344]
## What happened?
Using the current NPM and/or Github version (1.0.3) I'm running into the same problem.  I'm crawling an https site that depends on older ciphers (IIS server).  I'm trying to use the `fetchstart` event to override the default cipher suite in the requestOptions, using the `ciphers` property, as mentioned [here](https://nodejs.org/docs/latest/api/https.html#https_https_request_options_callback)

> **ciphers:** A string describing the ciphers to use or exclude. Consult https://www.openssl.org/docs/man1.0.2/apps/ciphers.html#CIPHER-LIST-FORMAT for details on the format.

## Steps to reproduce the problem

I'm using `fetchstart` to try to change the ciphers, with no luck:
```javascript
const Crawler            = require("simplecrawler");
const crawler            = new Crawler("https://applications.bmi.com/Security/Login.aspx");
crawler.maxConcurrency   = 3;
crawler.maxDepth         = 2;
crawler.on("fetchstart", function(queueItem, requestOptions){
    requestOptions.ciphers = 'DES-CBC3-SHA';
});
crawler.on("fetchclienterror", function (queueItem, err) {
    console.error(err);
});
crawler.on("fetchcomplete", function () {
    console.log("Fetched a resource!");
});
crawler.start();
```
results in:
```
{ Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1111:19)
    at TLSSocket.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' }
```

When this works properly, I'd get a 302 response code, as shown by this example:
```javascript
const https = require("https");
var req = https.request({
    host    : 'applications.bmi.com',
    port    : 443,
    path    : '/Security/Login.aspx',
    method  : 'GET',
    ciphers : 'DES-CBC3-SHA',
}, (res) => console.log("done", res.statusCode));
req.end();
```

## Current workaround (and proof it's probably a small issue)
I'm not sure where `fetchstart` (or my understanding of it) is falling down, but if I modify `crawler.js` and change `Crawler.prototype.getRequestOptions`  to add a new crawler option like this:
 ```javascript
    if (crawler.ciphers){
        requestOptions.ciphers = crawler.ciphers;
    }
```

and then instantiate the Crawler like this:

```javascript
const crawler            = new Crawler("https://bad-iis-site.com/");
crawler.maxConcurrency   = 3;
crawler.maxDepth         = 2;
crawler.respectRobotsTxt = false;
crawler.ciphers          = 'DES-CBC3-SHA';
```
I can successfully crawl the problematic site.  This makes me think my `fetchstart` alterations aren't being passed back to the `https` client before the request.

Thanks for the great module and any help you can provide!

**Comment by cgiffard** [comment]
Huh, that looks like somehow, requestOptions is being ignored or discarded! I'll have a look into this later this evening. :) Sorry this has caused you hassle!

(As a total aside I'll happily admit that the implicit mutation is not a wonderful API for changing request headers, so I'd be happy to hear suggestions!)

**Comment by EyePulp** [comment]
Well... the most explicit route would be an optional function on the crawler that would be called (if provided) at the bottom of  `Crawler.prototype.getRequestOptions`: 
```javascript
    if (typeof crawler.overrideRequestOptions === 'function'){
       return crawler.overrideRequestOptions(queueItem,requestOptions); 
    }

    return requestOptions;
```

and the function would look like this:
```javascript
crawler.overrideRequestOptions = function(queueItem, requestOptions){
    requestOptions.foo = "bar";
    requestOptions.headers.fizz = "buzz";
    return requestOptions;
}
```

It's synchronous, so maybe not everything to everyone, but it's a start, perhaps. If you'd like a PR it's easy enough for me to add one.  However, I understand if it presents a conflict with your intent for `fetchstart` -- It's usually best to have one "correct" way to do things, and my approach may not be it.

Thanks!
